name: secugenfplib
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/imsajib02/SecugenFpLib

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.9
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.fdxpro.secugenfplib
        pluginClass: SecugenfplibPlugin
